name: meter_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.1.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  random_name_generator: ^1.1.0
  riverpod_annotation: ^2.3.5
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  uuid: ^4.4.0
  share_plus: ^9.0.0
  pdf: ^3.10.4
  printing: ^5.11.0
  fpdart: ^1.1.0
  supabase_flutter: ^2.5.3
  internet_connection_checker_plus: ^2.4.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  path_provider: ^2.1.1
  path: ^1.9.0
  url_launcher: ^6.0.20
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.3.12
  isar_generator: ^3.0.5

dependency_overrides:
  analyzer: ^6.5.0
  meta: ^1.14.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
