name: meter_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  random_name_generator: ^1.1.0
  riverpod_annotation: ^2.3.5
  flutter_bloc: ^9.1.1
  get_it: ^7.6.7
  uuid: ^4.4.0
  share_plus: ^10.0.2
  pdf: ^3.10.4
  printing: ^5.11.0
  fpdart: ^1.1.0
  supabase_flutter: ^2.5.3
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.1
#  flutter_facebook_auth: ^7.0.1
#  flutter_secure_storage: ^9.2.2
  internet_connection_checker_plus: ^2.7.2
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7
  isar: ^3.0.5
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  path_provider: ^2.1.1
  path: ^1.9.0
  url_launcher: ^6.3.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  flutter_typeahead: ^5.2.0
  rxdart: ^0.28.0
  geocoding: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  skeletonizer: ^1.4.2
  animations: ^2.0.11
  wolt_modal_sheet: ^0.9.3
  youtube_player_flutter: ^9.1.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_messaging: ^15.1.6
  modal_bottom_sheet: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  connectivity_plus: ^6.1.4
  flutter_speed_dial: ^7.0.0
  confetti: ^0.8.0
  change_app_package_name: ^1.5.0
  purchases_flutter: ^9.9.0
  logger: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.6.7
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.14
  isar_generator: ^3.0.5
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  analyzer: ^6.7.0
  custom_lint_visitor: ^1.0.0+6.7.0
  meta: ^1.14.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/metrashop_icon.png"
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-Medium.ttf
          - asset: assets/fonts/Poppins-Bold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
