// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEZpo-jaMINgkaNvUV5JzmWyfXneUs4w8',
    appId: '1:1088476245042:web:6bad22eb166388ceaa602b',
    messagingSenderId: '1088476245042',
    projectId: 'meterapp-fe4fe',
    authDomain: 'meterapp-fe4fe.firebaseapp.com',
    storageBucket: 'meterapp-fe4fe.firebasestorage.app',
    measurementId: 'G-1Z3N2MPZD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV0QMntbgGXeFJhgwK9FWxWGaDm8QI8SM',
    appId: '1:1088476245042:android:eba50f6d89a37d35aa602b',
    messagingSenderId: '1088476245042',
    projectId: 'meterapp-fe4fe',
    storageBucket: 'meterapp-fe4fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKHr89no_A8eizvPTXTXO2jl61S0yY5F0',
    appId: '1:1088476245042:ios:2a9e686e950980c5aa602b',
    messagingSenderId: '1088476245042',
    projectId: 'meterapp-fe4fe',
    storageBucket: 'meterapp-fe4fe.firebasestorage.app',
    iosBundleId: 'com.example.meterApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKHr89no_A8eizvPTXTXO2jl61S0yY5F0',
    appId: '1:1088476245042:ios:68aecea3de6ff064aa602b',
    messagingSenderId: '1088476245042',
    projectId: 'meterapp-fe4fe',
    storageBucket: 'meterapp-fe4fe.firebasestorage.app',
    iosBundleId: 'com.example.meterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEZpo-jaMINgkaNvUV5JzmWyfXneUs4w8',
    appId: '1:1088476245042:web:3be9387eaf985ae7aa602b',
    messagingSenderId: '1088476245042',
    projectId: 'meterapp-fe4fe',
    authDomain: 'meterapp-fe4fe.firebaseapp.com',
    storageBucket: 'meterapp-fe4fe.firebasestorage.app',
    measurementId: 'G-FSZDZTX5KR',
  );

}