// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvzEqe_sq-0fyQTy48eLiaAJwdQy9Yyvg',
    appId: '1:265588480754:web:9a63f352b1b25bccf98e6b',
    messagingSenderId: '265588480754',
    projectId: 'metrashop-1d311',
    authDomain: 'metrashop-1d311.firebaseapp.com',
    storageBucket: 'metrashop-1d311.firebasestorage.app',
    measurementId: 'G-M2LRTFB5KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNQqrJPkAounoQ2aNLQFIVD5oPdSWJ8YQ',
    appId: '1:265588480754:android:0f04b5af4b05c42df98e6b',
    messagingSenderId: '265588480754',
    projectId: 'metrashop-1d311',
    storageBucket: 'metrashop-1d311.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmhVbXzkDaApbvROotSApkVOw2H538xs0',
    appId: '1:265588480754:ios:ec3476cb60c687cff98e6b',
    messagingSenderId: '265588480754',
    projectId: 'metrashop-1d311',
    storageBucket: 'metrashop-1d311.firebasestorage.app',
    iosBundleId: 'com.mts.metrashop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmhVbXzkDaApbvROotSApkVOw2H538xs0',
    appId: '1:265588480754:ios:04862fd6217c8f83f98e6b',
    messagingSenderId: '265588480754',
    projectId: 'metrashop-1d311',
    storageBucket: 'metrashop-1d311.firebasestorage.app',
    iosBundleId: 'com.mts.metrashop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvzEqe_sq-0fyQTy48eLiaAJwdQy9Yyvg',
    appId: '1:265588480754:web:49c43568d029fbb2f98e6b',
    messagingSenderId: '265588480754',
    projectId: 'metrashop-1d311',
    authDomain: 'metrashop-1d311.firebaseapp.com',
    storageBucket: 'metrashop-1d311.firebasestorage.app',
    measurementId: 'G-CPXXHC1L9H',
  );

}